MYSQL_USER='scu_douyin'
MYSQL_PASSWORD='JSs3EXHt5mGD5DPy'
MYSQL_PORT=3306
MYSQL_DB='app'
MYSQL_HOST='47.242.248.7'

# MYSQL_USER='root'
# MYSQL_PASSWORD='root'
# MYSQL_PORT=3306
# MYSQL_DB='douyin'
# MYSQL_HOST='localhost'
